apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-coder-next-model
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Gi
