apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- amd-device-plugin.yaml

helmCharts:
- name: nvidia-device-plugin
  repo: https://nvidia.github.io/k8s-device-plugin
  version: 0.17.1
  releaseName: nvidia-device-plugin
  namespace: kube-system
  valuesFile: nvidia-values.yaml
