apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
namePrefix: n8n-

resources:
- ../base

commonLabels:
  agent: n8n

images:
- name: ghcr.io/ergoshear/n8n
  newName: ghcr.io/ergoshear/n8n
  newTag: 367afc5