apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
namePrefix: pi-coder-

resources:
- ../base

patches:
- target:
    kind: Deployment
    name: fedora-44-deployment
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/ports
    - op: add
      path: /spec/template/spec/containers/0/stdin
      value: true
    - op: add
      path: /spec/template/spec/containers/0/tty
      value: true
- target:
    kind: Service
    name: fedora-44-service
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Service
    metadata:
      name: fedora-44-service

commonLabels:
  agent: pi-coder

images:
- name: ghcr.io/ergoshear/agent
  newName: ghcr.io/ergoshear/pi-coder
  newTag: 753875b