apiVersion: v1
kind: Service
metadata:
  name: sandbox-api
spec:
  type: ClusterIP
  selector:
    app: sandbox-api
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: grpc
    port: 9090
    targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-runner-1
spec:
  type: ClusterIP
  selector:
    app: sandbox-runner-1
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: control-grpc
    port: 9091
    targetPort: control-grpc