apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devstral-small-2-model
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 32Gi
