apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-ergoshear-dev
spec:
  secretName: argocd-ergoshear-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - argocd.ergoshear.dev