apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- install.yaml
- repository-secret.yaml
- certificate.yaml
- ingress.yaml

patches:
- path: argocd-cm-patch.yaml