apiVersion: apps/v1
kind: Deployment
metadata:
  name: fedora-44-deployment
  namespace: agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora-44
  template:
    metadata:
      labels:
        app: fedora-44
    spec:
      containers:
      - name: agent
        image: ghcr.io/ergoshear/agent:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80