apiVersion: v1
kind: Service
metadata:
  name: fedora-44-service
  namespace: default
spec:
  selector:
    app: fedora-44
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: LoadBalancer