apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- metallb
- cert-manager
- cert-manager-issuer
- external-dns
- tailscale-operator
- agent-ingress
- hermes-agent
- code-server
- n8n
- n8n-sandbox
- searxng
- olla
