apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ergoshear-dev
spec:
  secretName: ergoshear-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hermes-agent.ergoshear.dev
  - n8n.ergoshear.dev
  - pi.ergoshear.dev
  - olla.ergoshear.dev